### ISSUE TITLE
Exception: 'DataFrame' object has no attribute 'sort'

### ISSUE THREAD

**Issue by smondet** [GauravPandeyLab/datasink#1]
I was trying to build/test datasink, and hit an isssue.

Building this `Dockerfile` 

```
FROM ubuntu
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get -y install groovy cython python-numpy python-scipy python-pip unzip curl git
RUN pip install -U pandas scikit-learn
RUN curl -O -L http://prdownloads.sourceforge.net/weka/weka-3-7-10.zip
RUN unzip weka-3-7-10.zip
RUN cp weka-3-7-10/weka.jar /usr/share/java
RUN git clone https://github.com/shwhalen/datasink.git
WORKDIR ./datasink
RUN make
ENV CLASSPATH $CLASSPATH:/usr/share/java/weka.jar
ENV JAVA_OPTS "-Xmx4g"
```

`combine.py` fails with what looks like

```
...
[Parallel(n_jobs=-1)]: Done 191 tasks      | elapsed:  6.1min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  6.1min
[Parallel(n_jobs=-1)]: Done 193 tasks      | elapsed:  6.1min
[Parallel(n_jobs=-1)]: Done 198 out of 200 | elapsed:  6.3min remaining:    3.8s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:  6.4min finished
Traceback (most recent call last):
  File "combine.py", line 53, in <module>
    concat(dirname_dfs, axis = 1).sort().to_csv(f)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'
```

Which looks like a problem with the default version of Pandas picked up by `pip`.

**Comment by smondet** [comment]
OK with

```
RUN pip install -U pandas==0.17.0 scikit-learn
```

it works!

(it just displays a warning:

```
combine.py:53: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  concat(dirname_dfs, axis = 1).sort().to_csv(f)
combine.py:68: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  concat(dirname_dfs, axis = 1).sort().to_csv(f)
```
)
